spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database

  h2:
    console.enabled: true

  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: <your gmail account>
    password: <your gmail app password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    generic-properties:
      properties:
        enforceHistoryTimeToLive: false

